pipeline:
  check:
    image: nixpkgs/nix-flakes:latest
    pull: true
    commands:
      - mkdir -p ~/.config/nix
      - echo "sandbox = false" >> ~/.config/nix/nix.conf
      - echo "substituters = s3://nix-store?endpoint=objects.cyplo.dev&scheme=https&region=cyplodev https://cache.nixos.org/" >> ~/.config/nix/nix.conf
      - export AWS_ACCESS_KEY_ID="nix-builder"
      - export AWS_SECRET_ACCESS_KEY="$MINIO_NIX_BUILDER_KEY"
      - nix build
      - nix flake check
      - nix develop -c ./scripts/package.sh
      - nix copy --all --substitute-on-destination --to 's3://nix-store?endpoint=objects.cyplo.dev&scheme=https&region=cyplodev'
    secrets: [ cargo_registry_token , minio_nix_builder_key ]

  publish:
    image: nixpkgs/nix-flakes:latest
    pull: true
    commands:
      - mkdir -p ~/.config/nix
      - echo "sandbox = false" >> ~/.config/nix/nix.conf
      - echo "substituters = s3://nix-store?endpoint=objects.cyplo.dev&scheme=https&region=cyplodev https://cache.nixos.org/" >> ~/.config/nix/nix.conf
      - export AWS_ACCESS_KEY_ID="nix-builder"
      - export AWS_SECRET_ACCESS_KEY="$MINIO_NIX_BUILDER_KEY"
      - nix develop -c ./scripts/release.sh
      - nix copy --all --substitute-on-destination --to 's3://nix-store?endpoint=objects.cyplo.dev&scheme=https&region=cyplodev'
    secrets: [ cargo_registry_token , minio_nix_builder_key ]
