pipeline:
  check:
    image: nixpkgs/nix-flakes:latest
    pull: true
    commands:
      - mkdir -p ~/.config/nix
      - echo "sandbox = false" >> ~/.config/nix/nix.conf
      - echo "substituters = s3://nix-store?endpoint=objects.cyplo.dev&scheme=https&region=cyplodev https://cache.nixos.org/" >> ~/.config/nix/nix.conf
      - echo "extra-trusted-public-keys = cyplodev-store-key:a/+PEufePs7giWqYyRqy+TgUKLMbY+RQuJQu2aUjdl8=" >> ~/.config/nix/nix.conf
      - export AWS_ACCESS_KEY_ID="nix-builder"
      - export AWS_SECRET_ACCESS_KEY="$MINIO_NIX_BUILDER_KEY"
      - echo "$STORE_SECRET_KEY" > ~/.store-secret-key
      - nix store sign --key-file ~/.store-secret-key --all
      - nix copy --all --substitute-on-destination --to 's3://nix-store?endpoint=objects.cyplo.dev&scheme=https&region=cyplodev'
    secrets: [ minio_nix_builder_key , store_secret_key ]

  publish:
    image: nixpkgs/nix-flakes:latest
    pull: true
    commands:
      - mkdir -p ~/.config/nix
      - echo "sandbox = false" >> ~/.config/nix/nix.conf
      - echo "substituters = s3://nix-store?endpoint=objects.cyplo.dev&scheme=https&region=cyplodev https://cache.nixos.org/" >> ~/.config/nix/nix.conf
      - echo "extra-trusted-public-keys = cyplodev-store-key:a/+PEufePs7giWqYyRqy+TgUKLMbY+RQuJQu2aUjdl8=" >> ~/.config/nix/nix.conf
      - export AWS_ACCESS_KEY_ID="nix-builder"
      - export AWS_SECRET_ACCESS_KEY="$MINIO_NIX_BUILDER_KEY"
      - mkdir -p ~/.ssh/
      - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
      - echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_ed25519.pub
      - chmod 0400 ~/.ssh/id_ed25519
      - nix develop -c ./scripts/release.sh
      - echo "$STORE_SECRET_KEY" > ~/.store-secret-key
      - nix store sign --key-file ~/.store-secret-key --all
      - nix copy --all --substitute-on-destination --to 's3://nix-store?endpoint=objects.cyplo.dev&scheme=https&region=cyplodev'
    secrets: [ cargo_registry_token , minio_nix_builder_key , ssh_private_key , ssh_public_key , store_secret_key ]
