pipeline:
  check_and_publish:
    image: nixpkgs/nix-flakes:latest
    pull: true
    commands:
      - nix-shell --pure --run "./scripts/test.sh"
      - nix-shell --pure --run "./scripts/package.sh"
      - nix-shell --pure --run "./scripts/release.sh"
    secrets: [ cargo_registry_token ]
