pipeline:

  publish:
    image: nixpkgs/nix-flakes:latest
    pull: true
    commands:
      - mkdir -p ~/.config/nix
      - echo "sandbox = false" >> ~/.config/nix/nix.conf
      - echo "substituters = s3://nix-store?endpoint=objects.cyplo.dev&scheme=https&region=cyplodev https://cache.nixos.org/" >> ~/.config/nix/nix.conf
      - echo "trusted-public-keys = cyplodev-store-key:a/+PEufePs7giWqYyRqy+TgUKLMbY+RQuJQu2aUjdl8= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=" >> ~/.config/nix/nix.conf
      - export AWS_ACCESS_KEY_ID="nix-builder"
      - export AWS_SECRET_ACCESS_KEY="$MINIO_NIX_BUILDER_KEY"
      - mkdir -p ~/.ssh/
      - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
      - echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_ed25519.pub
      - chmod 0400 ~/.ssh/id_ed25519
      - nix shell nixpkgs#tailscale -c tailscale version
      - nix shell nixpkgs#tailscale -c tailscaled --tun=userspace-networking --socks5-server=localhost:1055 --outbound-http-proxy-listen=localhost:1055 --state="mem:" &
      - sleep 1
      - nix shell nixpkgs#tailscale -c tailscale up -authkey $TAILSCALE_KEY
      - nix shell nixpkgs#tailscale -c tailscale status
      - nix develop -c ./scripts/release.sh
      - echo "$STORE_SECRET_KEY" > ~/.store-secret-key
      - nix store sign --key-file ~/.store-secret-key --all
      - nix copy --all --substitute-on-destination --to 's3://nix-store?endpoint=objects.cyplo.dev&scheme=https&region=cyplodev'
    secrets: [ cargo_registry_token , minio_nix_builder_key , ssh_private_key , ssh_public_key , store_secret_key ]
