pipeline:
  check_and_publish:
    image: nixpkgs/nix-flakes:latest
    pull: true
    commands:
      - nix build
      - nix flake check
      - nix shell -c ./scripts/package.sh
      - nix shell -c ./scripts/release.sh
    secrets: [ cargo_registry_token ]
