pipeline:
  check_and_publish:
    image: nixpkgs/nix-flakes:latest
    pull: true
    commands:
      - mkdir -p ~/.config/nix
      - echo "sandbox = false" >> ~/.config/nix/nix.conf 
      - nix build 
      - nix flake check
      - nix develop -c ./scripts/package.sh
      - nix develop -c ./scripts/release.sh
    secrets: [ cargo_registry_token ]
