pipeline:
  push_to_github:
    image: plugins/git
    pull: true
    commands:
      - git fetch --unshallow origin
      - git remote add github https://cyplo:$GITHUB_TOKEN@github.com/cyplo/genpass.git
      - git push github --all --force
    secrets: [ github_token ]
